-- Feature 004 · modelo-dados-core (dona). GERADO por scripts/generate-category-seed.ts a partir
-- de src/domain/core/default-categories.ts — não edite à mão (research R-12).
-- Modelos de categoria (data-model §4) e catálogo de instituições de referência (§2.2, FR-005).

INSERT INTO public.category_templates (key, parent_key, name, kind, system_key, sort_order) VALUES
  ('food', NULL, 'Alimentação', 'expense', NULL, 10),
  ('food.groceries', 'food', 'Mercado', 'expense', NULL, 10),
  ('food.restaurants', 'food', 'Restaurantes', 'expense', NULL, 20),
  ('food.delivery', 'food', 'Delivery', 'expense', NULL, 30),
  ('food.bakery_coffee', 'food', 'Padaria e café', 'expense', NULL, 40),
  ('food.snacks', 'food', 'Lanches', 'expense', NULL, 50),
  ('housing', NULL, 'Moradia', 'expense', NULL, 20),
  ('housing.rent_mortgage', 'housing', 'Aluguel ou financiamento', 'expense', NULL, 10),
  ('housing.condo_fee', 'housing', 'Condomínio', 'expense', NULL, 20),
  ('housing.electricity', 'housing', 'Energia', 'expense', NULL, 30),
  ('housing.water', 'housing', 'Água', 'expense', NULL, 40),
  ('housing.gas', 'housing', 'Gás', 'expense', NULL, 50),
  ('housing.internet_tv', 'housing', 'Internet e TV', 'expense', NULL, 60),
  ('housing.maintenance', 'housing', 'Manutenção e reforma', 'expense', NULL, 70),
  ('housing.furniture', 'housing', 'Móveis e decoração', 'expense', NULL, 80),
  ('transport', NULL, 'Transporte', 'expense', NULL, 30),
  ('transport.fuel', 'transport', 'Combustível', 'expense', NULL, 10),
  ('transport.ride_hailing', 'transport', 'Aplicativos de transporte', 'expense', NULL, 20),
  ('transport.public_transport', 'transport', 'Transporte público', 'expense', NULL, 30),
  ('transport.parking_tolls', 'transport', 'Estacionamento e pedágio', 'expense', NULL, 40),
  ('transport.vehicle_maintenance', 'transport', 'Manutenção do veículo', 'expense', NULL, 50),
  ('transport.vehicle_taxes', 'transport', 'Seguro, IPVA e licenciamento', 'expense', NULL, 60),
  ('health', NULL, 'Saúde', 'expense', NULL, 40),
  ('health.health_plan', 'health', 'Plano de saúde', 'expense', NULL, 10),
  ('health.pharmacy', 'health', 'Farmácia', 'expense', NULL, 20),
  ('health.appointments', 'health', 'Consultas e exames', 'expense', NULL, 30),
  ('health.dentist', 'health', 'Dentista', 'expense', NULL, 40),
  ('health.fitness', 'health', 'Academia e esportes', 'expense', NULL, 50),
  ('education', NULL, 'Educação', 'expense', NULL, 50),
  ('education.courses', 'education', 'Cursos', 'expense', NULL, 10),
  ('education.books', 'education', 'Livros e materiais', 'expense', NULL, 20),
  ('education.tuition', 'education', 'Mensalidade escolar', 'expense', NULL, 30),
  ('leisure', NULL, 'Lazer', 'expense', NULL, 60),
  ('leisure.events', 'leisure', 'Cinema, shows e eventos', 'expense', NULL, 10),
  ('leisure.bars', 'leisure', 'Bares e baladas', 'expense', NULL, 20),
  ('leisure.hobbies', 'leisure', 'Hobbies', 'expense', NULL, 30),
  ('leisure.games', 'leisure', 'Jogos', 'expense', NULL, 40),
  ('travel', NULL, 'Viagens', 'expense', NULL, 70),
  ('travel.tickets', 'travel', 'Passagens', 'expense', NULL, 10),
  ('travel.lodging', 'travel', 'Hospedagem', 'expense', NULL, 20),
  ('travel.tours', 'travel', 'Passeios', 'expense', NULL, 30),
  ('travel.foreign_expenses', 'travel', 'Câmbio e despesas no exterior', 'expense', NULL, 40),
  ('shopping', NULL, 'Compras', 'expense', NULL, 80),
  ('shopping.clothing', 'shopping', 'Roupas e calçados', 'expense', NULL, 10),
  ('shopping.electronics', 'shopping', 'Eletrônicos', 'expense', NULL, 20),
  ('shopping.home_goods', 'shopping', 'Casa e utilidades', 'expense', NULL, 30),
  ('shopping.gifts', 'shopping', 'Presentes', 'expense', NULL, 40),
  ('subscriptions', NULL, 'Assinaturas e serviços', 'expense', NULL, 90),
  ('subscriptions.streaming', 'subscriptions', 'Streaming', 'expense', NULL, 10),
  ('subscriptions.software', 'subscriptions', 'Aplicativos e software', 'expense', NULL, 20),
  ('subscriptions.mobile_phone', 'subscriptions', 'Telefonia celular', 'expense', NULL, 30),
  ('subscriptions.clubs', 'subscriptions', 'Clubes e associações', 'expense', NULL, 40),
  ('personal_care', NULL, 'Cuidados pessoais', 'expense', NULL, 100),
  ('personal_care.salon', 'personal_care', 'Salão e barbearia', 'expense', NULL, 10),
  ('personal_care.cosmetics', 'personal_care', 'Cosméticos e higiene', 'expense', NULL, 20),
  ('pets', NULL, 'Pets', 'expense', NULL, 110),
  ('pets.pet_supplies', 'pets', 'Ração e produtos', 'expense', NULL, 10),
  ('pets.vet', 'pets', 'Veterinário', 'expense', NULL, 20),
  ('family', NULL, 'Família e filhos', 'expense', NULL, 120),
  ('family.school_daycare', 'family', 'Escola e creche', 'expense', NULL, 10),
  ('family.allowance', 'family', 'Mesada', 'expense', NULL, 20),
  ('family.kids_items', 'family', 'Brinquedos e roupas infantis', 'expense', NULL, 30),
  ('taxes_fees', NULL, 'Impostos, tarifas e juros', 'expense', NULL, 130),
  ('taxes_fees.bank_fees', 'taxes_fees', 'Tarifas bancárias', 'expense', 'bank_fees', 10),
  ('taxes_fees.interest_fines', 'taxes_fees', 'Juros e multas', 'expense', NULL, 20),
  ('taxes_fees.iof', 'taxes_fees', 'IOF', 'expense', NULL, 30),
  ('taxes_fees.taxes', 'taxes_fees', 'Impostos (IR, IPTU, outros)', 'expense', NULL, 40),
  ('taxes_fees.card_annual_fee', 'taxes_fees', 'Anuidade de cartão', 'expense', NULL, 50),
  ('donations', NULL, 'Doações', 'expense', NULL, 140),
  ('donations.donations', 'donations', 'Doações', 'expense', NULL, 10),
  ('donations.tithes', 'donations', 'Dízimo e contribuições', 'expense', NULL, 20),
  ('other_expenses', NULL, 'Outros gastos', 'expense', NULL, 150),
  ('other_expenses.cash_withdrawals', 'other_expenses', 'Saques em dinheiro', 'expense', NULL, 10),
  ('other_expenses.misc', 'other_expenses', 'Diversos', 'expense', NULL, 20),
  ('salary', NULL, 'Salário', 'income', 'salary', 160),
  ('salary.salary', 'salary', 'Salário', 'income', NULL, 10),
  ('salary.thirteenth', 'salary', '13º salário', 'income', NULL, 20),
  ('salary.vacation', 'salary', 'Férias', 'income', NULL, 30),
  ('salary.bonus', 'salary', 'PLR e bônus', 'income', NULL, 40),
  ('extra_income', NULL, 'Renda extra', 'income', NULL, 170),
  ('extra_income.freelance', 'extra_income', 'Freelance', 'income', NULL, 10),
  ('extra_income.sales', 'extra_income', 'Vendas', 'income', NULL, 20),
  ('extra_income.rent_received', 'extra_income', 'Aluguéis recebidos', 'income', NULL, 30),
  ('yields', NULL, 'Rendimentos', 'income', NULL, 180),
  ('yields.interest', 'yields', 'Juros e rendimentos', 'income', NULL, 10),
  ('yields.dividends', 'yields', 'Dividendos', 'income', NULL, 20),
  ('yields.cashback', 'yields', 'Cashback', 'income', NULL, 30),
  ('refunds', NULL, 'Reembolsos', 'income', NULL, 190),
  ('refunds.chargebacks', 'refunds', 'Estornos', 'income', NULL, 10),
  ('refunds.expense_refunds', 'refunds', 'Reembolsos de despesas', 'income', NULL, 20),
  ('other_income', NULL, 'Outras receitas', 'income', NULL, 200),
  ('other_income.gifts_received', 'other_income', 'Presentes recebidos', 'income', NULL, 10),
  ('other_income.misc', 'other_income', 'Diversos', 'income', NULL, 20),
  ('internal_transfer', NULL, 'Transferência entre contas', 'neutral', 'internal_transfer', 210),
  ('card_payment', NULL, 'Pagamento de fatura', 'neutral', 'card_payment', 220),
  ('investments', NULL, 'Investimentos', 'neutral', NULL, 230),
  ('investments.contributions', 'investments', 'Aplicações', 'neutral', NULL, 10),
  ('investments.redemptions', 'investments', 'Resgates', 'neutral', NULL, 20),
  ('uncategorized', NULL, 'Sem categoria', 'expense', 'uncategorized', 240);

INSERT INTO public.institutions (id, owner_id, name, kind, bank_code) VALUES
  ('00000000-0000-4000-a000-000000000323', NULL, 'Mercado Pago', 'digital_wallet', '323'),
  ('00000000-0000-4000-a000-000000000104', NULL, 'Caixa Econômica Federal', 'bank', '104'),
  ('00000000-0000-4000-a000-000000000380', NULL, 'PicPay', 'digital_wallet', '380'),
  ('00000000-0000-4000-a000-000000000336', NULL, 'C6 Bank', 'bank', '336'),
  ('00000000-0000-4000-a000-000000000260', NULL, 'Nubank', 'bank', '260'),
  ('00000000-0000-4000-a000-000000000077', NULL, 'Banco Inter', 'bank', '077'),
  ('00000000-0000-4000-a000-000000000341', NULL, 'Itaú', 'bank', '341'),
  ('00000000-0000-4000-a000-000000000237', NULL, 'Bradesco', 'bank', '237'),
  ('00000000-0000-4000-a000-000000000001', NULL, 'Banco do Brasil', 'bank', '001'),
  ('00000000-0000-4000-a000-000000000033', NULL, 'Santander', 'bank', '033'),
  ('00000000-0000-4000-a000-000000000999', NULL, 'Outra instituição', 'other', NULL);
